CREATE DATABASE QUANLYDIEMSINHVIEN ON PRIMARY
(
	NAME = QUANLYDIEMSINHVIEN_DATA,
	FILENAME = 'D:\BTTO\DATABASE\TUAN_1\0306201481_BTVN_TUAN_1\QUANLYDIEMSINHVIEN_DATA.MDF',
	SIZE=50MB,MAXSIZE=100MB,FILEGROWTH=5
),
(
	NAME = QUANLYDIEMSINHVIEN_DATA_2,
	FILENAME = 'D:\BTTO\DATABASE\TUAN_1\0306201481_BTVN_TUAN_1\QUANLYDIEMSINHVIEN_DATA_2.NDF',
	SIZE=40MB,MAXSIZE=UNLIMITED,FILEGROWTH=10%
)
LOG ON
(
	NAME= QUANLYDIEMSINHVIEN_LOG,
	FILENAME='D:\BTTO\DATABASE\TUAN_1\0306201481_BTVN_TUAN_1\QUANLYDIEMSINHVIEN_LOG.LDF',
	SIZE=10MB,MAXSIZE=UNLIMITED,FILEGROWTH=5MB
)

USE QUANLYDIEMSINHVIEN

CREATE TABLE SINHVIEN
(
	HoSV nvarchar(15),
	TenLot nvarchar(15),
	TenSV nvarchar(15),
	MSSV char(9),
	NgSinh date,
	NoiSinh nvarchar(40),
	Phai char(1),
	MaLop varchar(9),
	primary key (MSSV)
)

CREATE TABLE LOPHOC
(
	MaLop varchar(9),
	TenLop varchar(9),
	SiSo int,
	MaKhoa char(5),
	primary key(MaLop)
)

CREATE TABLE MONHOC
(
	MaMon varchar(9),
	TenMon nvarchar(16),
	SoTinChi int,
	primary key(MaMon)
)


CREATE TABLE KETQUA
(
	MSSV char(9),
	MaMon varchar(9),
	HocKy char(1),
	NamHoc char(4),
	LanThi int,
	Diem int,
	primary key(MSSV,MaMon)
)

ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN FOREIGN KEY (MaLop) REFERENCES LOPHOC(MaLop)
ALTER TABLE KETQUA ADD CONSTRAINT FK_KETQUA FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV)
ALTER TABLE KETQUA ADD CONSTRAINT FK_KETQUA_2 FOREIGN KEY (MaMon) REFERENCES MONHOC(MaMon)
