CREATE DATABASE    QLDA
ON PRIMARY
(    NAME= QLDA_Primary,
    FILENAME='D:\BTTO\DATABASE\TUAN_3\QLBH_P.mdf',
    SIZE=50MB,     MAXSIZE=UNLIMITED,     FILEGROWTH=100MB    )
LOG ON(
    NAME= QLDA_Log,
    FILENAME='D:\BTTO\DATABASE\TUAN_3\QLBH_log.ldf',
    SIZE=8MB,     MAXSIZE=UNLIMITED,     FILEGROWTH=10%)

USE QLDA;
GO
-- Tạo bảng Nhân Viên
CREATE TABLE NHANVIEN
(
    HONV nvarchar(15),
    TENLOT nvarchar(15),
    TENNV nvarchar(15),
    MANV char(9),
    NGSINH date,
    DCHI nvarchar(30),
    PHAI nvarchar(3),
    LUONG float,
    MA_NQL  char(9),
    PHG  int,
    PRIMARY KEY (MANV)
)

-- Tạo bảng Đề Án
CREATE TABLE DEAN
(
    TENDA nvarchar(15),
    MADA int,
    DDIEM_DA nvarchar(15),
    PHONG int,
    PRIMARY KEY (MADA)
)

-- Tạo bảng Công Việc
CREATE TABLE CONGVIEC
(
    MADA int,
    STT int,
    TEN_CONG_VIEC nvarchar(50),
    PRIMARY KEY (MADA, STT)
)

-- Tạo bảng Phòng Ban
CREATE TABLE PHONGBAN
(
    TENPHG nvarchar(15),
    MAPHG int,
    TRPHG char(9),
    NG_NHANCHUC date,
    PRIMARY KEY (MAPHG)
)

-- Tạo bảng Phân Công
CREATE TABLE PHANCONG
(
    MA_NVIEN  char(9),
    MADA int,
    STT int,
    THOIGIAN float,
    PRIMARY KEY (MA_NVIEN, MADA, STT)
)

-- Tạo bảng Thân Nhân
CREATE TABLE THANNHAN
(
    MA_NVIEN char(9),
    TENTN nvarchar(15),
    PHAI nvarchar(3),
    NGSINH date,
    QUANHE  nvarchar(15),
    PRIMARY KEY (MA_NVIEN, TENTN)
)

-- Tạo bảng Địa Điểm Phòng
CREATE TABLE DIADIEM_PHG
(
    MAPHG  int,
    DIADIEM nvarchar(15),
    PRIMARY KEY (MAPHG, DIADIEM)
)

ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN FOREIGN KEY(MA_NQL)REFERENCES NHANVIEN(MANV)
ALTER TABLE PHONGBAN ADD CONSTRAINT FK_PHONGBAN FOREIGN KEY(TRPHG)REFERENCES NHANVIEN(MANV)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_2 FOREIGN KEY(PHG)REFERENCES PHONGBAN(MAPHG)

--Câu 2 a i)
ALTER TABLE NHANVIEN NOCHECK CONSTRAINT FK_NHANVIEN_2

INSERT INTO NHANVIEN VALUES (N'Nguyễn', N'Thanh', N'Trúc', '004', '1/1/2000', N'200 Cống Quỳnh Q1, TP HCM',N'Nam',30000, null, 4)

--Câu 2 a ii)

INSERT INTO NHANVIEN VALUES (N'Nguyễn', N'Thanh', N'Trúc', '004', '1/1/2000', N'200 Cống Quỳnh Q1, TP HCM',N'Nữ',40000, null, 4)

--Câu 2 a iii)

INSERT INTO NHANVIEN VALUES (N'Nguyễn', N'Thanh', N'Trúc', '010', '1/1/2000', N'200 Cống Quỳnh Q1, TP HCM',N'Nữ',40000, null, 4)

--Câu 2 b i)

INSERT INTO NHANVIEN VALUES (N'Nguyễn', N'Thanh', N'Trúc', '010', '1/1/2000', N'200 Cống Quỳnh Q1,TP HCM',N'Nữ',40000, '011', 4)

--Câu 2 b ii)

INSERT INTO NHANVIEN VALUES (N'Nguyễn', N'Thanh', N'Trúc', '005', '1/1/2000', N'200 Cống Quỳnh Q1,TP HCM',N'Nữ',40000, '004', 4)

--Câu 3)
ALTER TABLE NHANVIEN
ADD CONSTRAINT C_NHANVIEN CHECK (PHAI = N'Nam' OR PHAI = N'Nữ')

--Câu 4)
ALTER TABLE DEAN
ADD CONSTRAINT U_DEAN UNIQUE (TENDA)

--Câu 5)
ALTER TABLE NHANVIEN
ADD NGAYVAOLAM DATE

UPDATE NHANVIEN SET NGAYVAOLAM = GETDATE()

INSERT INTO NHANVIEN VALUES (N'Nguyễn', N'Thanh', N'Trúc', '007', '1/1/2000', N'200 Cống Quỳnh Q1,TP HCM',N'Nữ',40000, '004', 4,NULL)
INSERT INTO NHANVIEN VALUES (N'Nguyễn', N'Thanh', N'Trúc', '008', '1/1/2000', N'200 Cống Quỳnh Q1,TP HCM',N'Nữ',40000, '004', 4,'1/1/2018')

--Câu 6)
ALTER TABLE NHANVIEN
ADD CONSTRAINT C_NHANVIEN_2 CHECK(NGSINH < NGAYVAOLAM)

--Câu 7)
CREATE RULE GIATRIDUONG
AS @giatri>0

EXEC SP_BINDRULE'GIATRIDUONG','NHANVIEN.PHG'

--Câu 8)

CREATE RULE TUOI
AS @range<='01/01/2003'
EXEC sp_bindrule 'TUOI','NHANVIEN.NGSINH'
INSERT INTO NHANVIEN VALUES (N'Nguyễn', N'Thanh', N'Trúc', '011', '12/31/2002', N'200 Cống Quỳnh Q1,TP HCM',N'Nữ',40000, '004', 4,NULL)

--Câu 9)
exec sp_unbindrule 'NHANVIEN.PHG'


--Câu 10)
exec sp_bindrule 'GIATRIDUONG','NHANVIEN.PHG'

--Câu 11)
exec sp_unbindrule 'NHANVIEN.PHG'
DROP RULE GIATRIDUONG

--Câu 12)
ALTER TABLE NHANVIEN DROP CONSTRAINT C_NHANVIEN_2

--Câu 13)
ALTER TABLE NHANVIEN NOCHECK CONSTRAINT FK_NHANVIEN, FK_NHANVIEN_2

--Câu 14)
ALTER TABLE NHANVIEN CHECK CONSTRAINT FK_NHANVIEN, FK_NHANVIEN_2

--Câu 15
ALTER INDEX PK__NHANVIEN__603F51141BA4624B ON NHANVIEN
DISABLE;

--Câu 16)
ALTER INDEX PK__NHANVIEN__603F51141BA4624B ON NHANVIEN
REBUILD;
